### DISCUSSION TITLE
Set heartbeat with RABBITMQ_USERNAME and RABBITMQ_PASSWORD in docker-compose file

### DISCUSSION THREAD

**Discussion by urvisism** [pika/pika#1491] [Q&A]
Hello folks,
I have been using RabbitMQ via bitnami/rabbitmq image since long time and periodically we face the given error,
"Consumers disconnect after long idle from RabbitMQ queue"
So, I did some research on the issue and found this solution about setting up heartbeat value, which is currently not defined anywhere in our set-up.
Solution link: https://github.com/pika/pika/discussions/1418
Till now, there is no .conf file configured in my docker-compose.yaml file. yaml file is given below.
```
networks:
  rabbitmq:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.255.0/24
          gateway: 172.16.255.1

services:

  rabbitmq:
    image: bitnami/rabbitmq:3.12.12
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-user}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-root}
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
      - RABBITMQ_PLUGINS=rabbitmq_management,rabbitmq_shovel,rabbitmq_shovel_management,rabbitmq_delayed_message_exchange
      - RABBITMQ_COMMUNITY_PLUGINS=https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.12.0/rabbitmq_delayed_message_exchange-3.12.0.ez
    volumes:
      - rabbitmq_data:/bitnami/rabbitmq/mnesia
    networks:
      - rabbitmq

volumes:
  rabbitmq_data:
```
But, when I add .conf in .yaml file, then It stops considering RABBITMQ_USERNAME & RABBITMQ_PASSWORD from environment as .conf file take precedence over environment variables. .yaml file after adding .conf is given below.
```
networks:
  rabbitmq:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.255.0/24
          gateway: 172.16.255.1

services:

  rabbitmq:
    image: bitnami/rabbitmq:3.12.12
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-user}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-root}
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
      - RABBITMQ_PLUGINS=rabbitmq_management,rabbitmq_shovel,rabbitmq_shovel_management,rabbitmq_delayed_message_exchange
      - RABBITMQ_COMMUNITY_PLUGINS=https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.12.0/rabbitmq_delayed_message_exchange-3.12.0.ez
    volumes:
      - rabbitmq_data:/bitnami/rabbitmq/mnesia
      - ./config/rabbitmq/rabbitmq.conf:/opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf:rw
    networks:
      - rabbitmq

volumes:
  rabbitmq_data:
```
So, how can I set heartbeat as well as USERNAME and PASSWORD simultaneously ? 
I want to set USERNAME and PASSWORD from the .env file.
