### ISSUE TITLE
async consumer ioloop hangs unexpectedly after rabbitmq 3.7.2 update

### ISSUE THREAD

**Issue by radzhome** [pika/pika#913]
Using the following example to create a consumer:
http://pika.readthedocs.io/en/0.10.0/examples/asynchronous_consumer_example.html

Under heavy load, the worker gets stuck, becomes idle and no exceptions. If you restart it its fine again. 

Tried rabbit 3.7.0(erlang 20.1.7.1) and 3.7.2(erlang 20.1.7.1) same issue. Strace shows the following is looping. Looks like its calling the callback function without consuming from queue anymore until restart:

```
[rad@feed4 ~]$ sudo strace -p 1817
strace: Process 1817 attached
epoll_wait(9,
[], 1023, 5000)           = 0
gettimeofday({1515528396, 907179}, NULL) = 0
epoll_wait(9, [], 1023, 5000)           = 0
gettimeofday({1515528401, 912598}, NULL) = 0
epoll_wait(9, [], 1023, 5000)           = 0
gettimeofday({1515528406, 917984}, NULL) = 0
epoll_wait(9, [], 1023, 5000)           = 0
gettimeofday({1515528411, 923459}, NULL) = 0
```

In order to re-create I had to consume millions of messages until the python script got hung and had to be force killed. No errors in log. I suspect the issue might be erlang, seems to be fine with rabbit 3.7.0(erlang 20.1.7). All tests done on pika 0.11.2.  

WORKAROUND: Stay on erlang 20.1.7.0 and rabbit 3.7.0 for now.

**Comment by lukebakken** [comment]
Thanks for the info. I have some follow-up questions:

* Have you tried Erlang 20.2 and newer? 19.3?
* What version of Python are you using?
* What operating system and version is running RabbitMQ and your Python code?
* Could you describe your environment? What are the specs of the machines running RabbitMQ, and your producers & consumers?
* Could you share code to reproduce this issue?

**Comment by radzhome** [comment]
Have you tried Erlang 20.2 and newer? 19.3?
What version of Python are you using?
* OS CentOS Linux release 7.4.1708 (Core)
* Python 2.7.5 in virtualenv
* I have an override service file:
```
[Service]
LimitNOFILE=65536
```
my rabbit config is:
```
%% -*- mode: erlang -*-
%% ----------------------------------------------------------------------------
%% RabbitMQ  Configuration File. /etc/rabbitmq/
%% Source https://github.com/rabbitmq/rabbitmq-server/blob/master/docs/rabbitmq.config.example
%% See https://www.rabbitmq.com/configure.html#configuration-file for details.
%% ----------------------------------------------------------------------------

[
  {
    rabbit, [
      {loopback_users, []},
      {log_levels, [{connection, error}, {channel, error}]},
      {disk_free_limit, {mem_relative, 0.1}},
      {tcp_listeners, [5672]},
      {heartbeat, 0},
      {frame_max, 0},
      {vm_memory_high_watermark, 0.6},
      {rates_mode, none},
      {collect_statistics, none}
    ]
  }
].
```
rabbit admin enabled. Here is my whole ansible provision:

```
# Import PGP Key for rabbitmq repo
- name: Import new RPM key for rabbitmq repo
  rpm_key: key=https://packagecloud.io/rabbitmq/erlang/gpgkey state=present
  ignore_errors: yes
  tags:
    - rabbitmq

# Enable repo for later updates
- name: enable erlang repo for rabbitmq
  template:
    src: rabbitmq_erlang.repo
    dest: /etc/yum.repos.d/rabbitmq_erlang.repo
    owner: root
    group: root
    mode: 0644
  tags:
    - rabbitmq

# Rabbit 3.6.15+ requires erlang 19.3.x, zero dependency erlang: https://github.com/rabbitmq/erlang-rpm/releases
# Rabbit 3.7.2 issues started along with 20.1.7.1, same ioloop issues seem to exist on 3.7.0
- name: yum list version of installed erlang
  shell: yum list installed erlang | grep erlang | awk '{print $2}' | cut -d'-' -f1 warn=no
  register: erlang_version
  tags:
    - rabbitmq

- name: yum remove erlang
  yum: pkg=erlang* state=absent update_cache=yes
  when: erlang_version['stdout'] != '20.1.7'  # Reverted from 20.1.7.1 to 20.1.7
  tags:
    - rabbitmq

# Backed up at https://mirror.fanxchange.com/centos/rabbit/erlang-20.1.7.1-1.el7.centos.x86_64.rpm
# Trying https://github.com/rabbitmq/erlang-rpm/releases/download/v20.1.7/erlang-20.1.7-1.el7.centos.x86_64.rpm
- name: install zero dependency erlang for rabbit
  yum:
    name: https://github.com/rabbitmq/erlang-rpm/releases/download/v20.1.7/erlang-20.1.7-1.el7.centos.x86_64.rpm
    state: present
    update_cache: yes
  when: erlang_version['stdout'] != '20.1.7'
  tags:
    - rabbitmq

- name: yum list version of installed rabbitmq-server
  shell: yum list installed rabbitmq-server | grep rabbitmq-server | awk '{print $2}' | cut -d'-' -f1 warn=no
  register: rabbit_version
  tags:
    - rabbitmq

- name: yum remove rabbitmq-server
  yum: pkg=rabbitmq-server state=absent
  when: rabbit_version['stdout'] != '3.7.0'  # Reverted from 3.7.2 due to problems
  tags:
    - rabbitmq

# Backup is at http://mirror.int.fanxchange.com/centos/rabbit/rabbitmq-server-3.7.2-1.el7.noarch.rpm
# Trying old https://dl.bintray.com/rabbitmq/all/rabbitmq-server/3.7.0/rabbitmq-server-3.7.0-1.el7.noarch.rpm
- name: install rabbitmq-server from rpm
  yum:
    name: https://dl.bintray.com/rabbitmq/all/rabbitmq-server/3.7.0/rabbitmq-server-3.7.0-1.el7.noarch.rpm
    state: present
    update_cache: yes
  when: rabbit_version['stdout'] != '3.7.0'
  tags:
    - rabbitmq

# Dir for socket descriptors override
- name: create /etc/systemd/system/rabbitmq-server.service.d/ dir
  file: path=/etc/systemd/system/rabbitmq-server.service.d state=directory
  tags:
    - rabbitmq

# Setup socket descriptors, see rabbitmqctl status
- name: /etc/systemd/system/rabbitmq-server.service.d/override.conf
  template: src=service.d.override.conf dest=/etc/systemd/system/rabbitmq-server.service.d/override.conf
            owner=root group=root mode=644
  notify: reload systemd
  tags:
    - rabbitmq

- name: /etc/rabbitmq/rabbitmq.config
  copy: src=../files/etc/rabbitmq/rabbitmq.config dest=/etc/rabbitmq/rabbitmq.config mode=444 owner=root group=root
  tags:
    - rabbitmq

# Using default config here for now
# Default location of rabbitmq.config and rabbitmq-env.conf is /etc/rabbitmq/
# https://www.rabbitmq.com/configure.html#configuration-file
#- name: /etc/rabbitmq/rabbitmq-env.conf
#  copy: src=../files/etc/rabbitmq/rabbitmq-env.conf dest=/etc/rabbitmq/rabbitmq-env.conf mode=444 owner=root group=root
#  tags:
#    - rabbitmq

- name: rabbitmq-server service
  systemd: name=rabbitmq-server state=restarted enabled=true daemon_reload=yes
  tags:
    - rabbitmq

- name: /etc/sudoers.d/queue-wheel
  copy: src=../files/etc/sudoers.d/queue-wheel dest=/etc/sudoers.d/queue-wheel owner=root group=root mode=444
  tags:
    - rabbitmq

- name: enable rabbitmq management ui
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  tags:
    - rabbitmq

- name: /usr/local/bin/check_rabbitmq.py
  copy: src=../files/usr/local/bin/check_rabbitmq.py dest=/usr/local/bin/check_rabbitmq.py mode=555 owner=root group=root
  tags:
    - rabbitmq
```

The consumers and publishers both running on t2.large, rabbit is also running on a t2.large aws instance, no credit issues on both.

The code is exactly a copy of the async consumer example. The publisher code is working properly the problem is lockup on the ioloop. This is the basically the code for the breaking consumer - http://pika.readthedocs.io/en/0.10.0/examples/asynchronous_consumer_example.html

My messages can get quite large, not sure if that has anything to do with it. I have to play around with it more. I can reproduce the issue when I pump prod data through it, but haven't been able to isolate the exact problem in my dev environment.

I haven't tried erlang 20.2 or newer and haven't tried erlang 19.3. I am using rabbits 0 dependency rabbit.
